/* eslint-disable */
// Generated by scripts/generate-contracts.mjs. Do not edit by hand.
// Source: backend/schema/city-os.schema.json, with a committed C0-compatible offline snapshot.

export interface AmbulanceSnapshot {
  call_id: string | null;
  id: string;
  node_id: number;
  status: AmbulanceStatus;
  target_node_id: number | null;
}

export type AmbulanceStatus = "available" | "repositioning" | "dispatched" | "on_scene" | "transporting" | "handoff" | "released";

export interface ApiError {
  code: string;
  message: string;
}

export interface ArtifactChecksum {
  algorithm: "sha256";
  value: string;
}

export interface ArtifactEntry {
  checksum: ArtifactChecksum;
  media_type: string;
  name: string;
  path: string;
}

export interface ArtifactManifest {
  artifacts: Array<ArtifactEntry>;
  schema_version: "1.0";
}

export interface BootstrapResponse {
  api_version: "1.0";
  bounds: GeographicBounds;
  city: "São Paulo";
  default_seed: number;
  fleet_size_bounds: FleetSizeBounds;
  forecast_horizon_minutes: 60;
  frame_interval_minutes: 5;
  h3_resolution: 8;
  layer_urls: {  };
  optimization_cadence_minutes: 15;
  scenarios: Array<ScenarioObservation>;
  simulation_duration_minutes: 360;
}

export type CallPriority = 1 | 2 | 3;

export interface CallSnapshot {
  h3_cell: string;
  id: string;
  node_id: number;
  occurred_at_minute: number;
  priority: CallPriority;
  response_seconds: number | null;
  status: CallStatus;
}

export type CallStatus = "pending" | "queued" | "dispatched" | "on_scene" | "transporting" | "handoff" | "completed" | "unserved";

export interface CameraObservation {
  bucket_start: string;
  camera_id: string;
  confidence: number;
  count: number;
  direction: string;
  edge_id: number;
  object_class: string;
}

export interface EdgeState {
  bucket_start: string;
  confidence: number;
  edge_id: number;
  flow_vph: number;
  occupancy_people: number;
  speed_kph: number;
  travel_seconds: number;
}

export interface FleetSizeBounds {
  default: number;
  maximum: number;
  minimum: number;
}

export interface GeographicBounds {
  max_latitude: number;
  max_longitude: number;
  min_latitude: number;
  min_longitude: number;
}

export interface H3Density {
  bucket_start: string;
  cell: string;
  confidence: number;
  density_people_km2: number;
  emergency_intensity_hour: number;
}

export interface MethodologyMetadata {
  calibration_description: string;
  calibration_target_seconds: 1260;
  call_tape_seed: number;
  data_label: "simulated";
}

export interface PairedMetrics {
  baseline: SimulationMetrics;
  optimized: SimulationMetrics;
}

export interface RoadEdge {
  capacity_vph: number;
  edge_id: number;
  free_flow_seconds: number;
  geometry_wkb: string;
  length_m: number;
  u: number;
  v: number;
}

export interface RoadNode {
  h3_cell: string;
  node_id: number;
  x: number;
  y: number;
}

export interface ScenarioObservation {
  affected_h3: Array<string>;
  blocked_edges: Array<number>;
  confidence: number;
  demand_multiplier: number;
  ends_at: string;
  id: string;
  source: ScenarioSource;
  starts_at: string;
  travel_penalty: number;
  type: ScenarioType;
}

export interface ScenarioParseRequest {
  text: string;
}

export interface ScenarioParseResponse {
  error: ApiError | null;
  observation: ScenarioObservation;
  used_fallback: boolean;
}

export type ScenarioSource = "simulated";

export type ScenarioType = "event" | "flood" | "demonstration" | "transit_disruption";

export interface SimulationCreatedResponse {
  simulation_id: string;
  status: "queued";
}

export interface SimulationFrame {
  active_scenario_ids: Array<string>;
  ambulances: Array<AmbulanceSnapshot>;
  calls: Array<CallSnapshot>;
  metrics: SimulationMetrics;
  minute: number;
  policy: SimulationPolicy;
}

export interface SimulationJobResponse {
  error: ApiError | null;
  methodology: MethodologyMetadata | null;
  metrics: PairedMetrics | null;
  request: SimulationRequest;
  simulation_id: string;
  status: SimulationJobStatus;
}

export type SimulationJobStatus = "queued" | "running" | "completed" | "failed";

export interface SimulationMetrics {
  mean_seconds: number | null;
  p50_seconds: number | null;
  p90_seconds: number | null;
  p95_seconds: number | null;
  policy: SimulationPolicy;
  queued_calls: number;
  reposition_km: number;
  unserved_calls: number;
  within_12m_pct: number | null;
  within_20m_pct: number | null;
  within_8m_pct: number | null;
  worst_district_p90_seconds: number | null;
}

export type SimulationPolicy = "baseline" | "optimized";

export interface SimulationRequest {
  fleet_size: number;
  scenario_id: string;
  seed: number;
}
